"""empty message

Revision ID: 61323b41ad8a
Revises: b3e25c07aca6
Create Date: 2024-10-20 12:55:55.784710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61323b41ad8a'
down_revision = 'b3e25c07aca6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=80), nullable=False),
    sa.Column('order_key', sa.String(length=80), nullable=False),
    sa.Column('created_via', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.Column('date_created', sa.String(length=80), nullable=False),
    sa.Column('discount_total', sa.String(length=80), nullable=False),
    sa.Column('discount_tax', sa.String(length=80), nullable=False),
    sa.Column('shipping_total', sa.String(length=80), nullable=False),
    sa.Column('total', sa.String(length=80), nullable=False),
    sa.Column('customer_id', sa.String(length=80), nullable=False),
    sa.Column('payment_method', sa.String(length=80), nullable=False),
    sa.Column('total_tax', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('role', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('username', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('billing', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('shipping', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('is_paying_customer', sa.String(length=120), nullable=False))
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.create_unique_constraint(None, ['shipping'])
        batch_op.create_unique_constraint(None, ['is_paying_customer'])
        batch_op.create_unique_constraint(None, ['first_name'])
        batch_op.create_unique_constraint(None, ['last_name'])
        batch_op.create_unique_constraint(None, ['role'])
        batch_op.create_unique_constraint(None, ['billing'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('is_paying_customer')
        batch_op.drop_column('shipping')
        batch_op.drop_column('billing')
        batch_op.drop_column('username')
        batch_op.drop_column('role')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    op.drop_table('order')
    # ### end Alembic commands ###
